# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrea Francesco Iuorio
#email_work: aa
email_personal: af@iuorio.eu
description: > # this means to ignore newlines until "baseurl:"
  Computer scientist and software developer by day, 
  CTF, hacker and MTG player by night.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://af.iuorio.eu" # the base hostname & protocol for your site
github_username: afiuorio91
mastodon_username: panzone
twitter_username: panzone91

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
